
  create table "public"."dailies" (
    "id" bigint generated by default as identity not null,
    "day" timestamp without time zone,
    "title" text,
    "content" text,
    "created_at" timestamp with time zone not null default now()
      );


CREATE UNIQUE INDEX dailies_pkey ON public.dailies USING btree (id);

alter table "public"."dailies" add constraint "dailies_pkey" PRIMARY KEY using index "dailies_pkey";

grant delete on table "public"."dailies" to "anon";

grant insert on table "public"."dailies" to "anon";

grant references on table "public"."dailies" to "anon";

grant select on table "public"."dailies" to "anon";

grant trigger on table "public"."dailies" to "anon";

grant truncate on table "public"."dailies" to "anon";

grant update on table "public"."dailies" to "anon";

grant delete on table "public"."dailies" to "authenticated";

grant insert on table "public"."dailies" to "authenticated";

grant references on table "public"."dailies" to "authenticated";

grant select on table "public"."dailies" to "authenticated";

grant trigger on table "public"."dailies" to "authenticated";

grant truncate on table "public"."dailies" to "authenticated";

grant update on table "public"."dailies" to "authenticated";

grant delete on table "public"."dailies" to "postgres";

grant insert on table "public"."dailies" to "postgres";

grant references on table "public"."dailies" to "postgres";

grant select on table "public"."dailies" to "postgres";

grant trigger on table "public"."dailies" to "postgres";

grant truncate on table "public"."dailies" to "postgres";

grant update on table "public"."dailies" to "postgres";

grant delete on table "public"."dailies" to "service_role";

grant insert on table "public"."dailies" to "service_role";

grant references on table "public"."dailies" to "service_role";

grant select on table "public"."dailies" to "service_role";

grant trigger on table "public"."dailies" to "service_role";

grant truncate on table "public"."dailies" to "service_role";

grant update on table "public"."dailies" to "service_role";


